export const BILL_TEMPLATE_REQUEST = 'BILL_TEMPLATE_REQUEST';
export const BILL_TEMPLATE_SUCCESS_STATUS_DRAFT = 'BILL_TEMPLATE_SUCCESS_STATUS_DRAFT';
export const BILL_TEMPLATE_SUCCESS_STATUS_READY = 'BILL_TEMPLATE_SUCCESS_STATUS_READY';
export const BILL_TEMPLATE_FAILURE = 'BILL_TEMPLATE_FAILURE';

