export const BILL_INDEX_REQUEST = 'BILL_INDEX_REQUEST';
export const BILL_INDEX_SUCCESS = 'BILL_INDEX_SUCCESS';
export const BILL_INDEX_FAILURE = 'BILL_INDEX_FAILURE';
export const BILL_INDEX_META = 'BILL_INDEX_META';
