export const MODAL_REVIEW_REQUEST         = 'MODAL_REVIEW_REQUEST';
export const MODAL_REVIEW_REQUEST_SUCCESS = 'MODAL_REVIEW_SUCCESS';
export const MODAL_REVIEW_REQUEST_FAILURE = 'MODAL_REVIEW_FAILURE';
export const MODAL_REVIEW_CHANGE          = 'MODAL_REVIEW_CHANGE';
export const MODAL_REVIEW_SAVE            = 'MODAL_REVIEW_SAVE';
export const MODAL_REVIEW_SAVE_SUCCESS    = 'MODAL_REVIEW_SAVE_SUCCESS';
export const MODAL_REVIEW_SAVE_FAILURE    = 'MODAL_REVIEW_SAVE_FAILURE';
