export const PAYMENT_INDEX_REQUEST = 'PAYMENT_INDEX_REQUEST';
export const PAYMENT_INDEX_SUCCESS = 'PAYMENT_INDEX_SUCCESS';
export const PAYMENT_INDEX_FAILURE = 'PAYMENT_INDEX_FAILURE';
export const PAYMENT_INDEX_META = 'PAYMENT_INDEX_META';
