export const paymentsData = [
  {
    house: 1,
    room: 115,
    payer: 'Такая Себе Фамилия',
    balance: 45,
  },
  {
    house: 1,
    room: 116,
    payer: 'Островский Леонид Николаевич',
    balance: 45,
  },
  {
    house: 1,
    room: 115,
    payer: 'Островский2 Леонид3 Николаевич4',
    balance: 45,
  },
  {
    house: 1,
    room: 116,
    payer: 'Островский Леонид Николаевич',
    balance: 45,
  },
  {
    house: 1,
    room: 116,
    payer: 'Островский Леонид Николаевич',
    balance: -145,
  },
  {
    house: 1,
    room: 117,
    payer: 'Котляревский Иван Федорович',
    balance: 245,
  },
  {
    house: 1,
    room: 118,
    payer: 'Петренко Петр Петрович',
    balance: -3145,
  },
  {
    house: 1,
    room: 119,
    payer: 'Иванов Иван Иванович',
    balance: 0,
  },
  {
    house: 1,
    room: 120,
    payer: 'Анархист Мудрый Васильевич',
    balance: -3145,
  },
  {
    house: 1,
    room: 121,
    payer: 'Прикол Угаш Морковный',
    balance: 0,
  },
  {
    house: 1,
    room: 122,
    payer: 'Клоун Ненорматив Петнистый',
    balance: 1120,
  },
  {
    house: 2,
    room: 10,
    payer: 'Злодей Хитрый Ненесытный',
    balance: -3145,
  },
  {
    house: 2,
    room: 11,
    payer: 'Карсь Судак Рыбный',
    balance: 0,
  },
  {
    house: 2,
    room: 12,
    payer: 'Мастер Мазать Сетны',
    balance: 1120,
  },
  {
    house: 1,
    room: 122,
    payer: 'Клоун Ненорматив Петнистый',
    balance: 1120,
  },
  {
    house: 2,
    room: 10,
    payer: 'Злодей Хитрый Ненесытный',
    balance: -3145,
  },
  {
    house: 2,
    room: 11,
    payer: 'Карсь Судак Рыбный',
    balance: 0,
  },
  {
    house: 2,
    room: 12,
    payer: 'Мастер Мазать Сетны',
    balance: 1120,
  },
];
